import type { Phrase } from "./types";

const STARTER_CREATED_AT = "2026-05-22T00:00:00.000Z";

export const STARTER_PHRASES: Phrase[] = [
  {
    id: "starter-001-really",
    japanese: "本当ですか？",
    chinese: "真的吗？",
    pinyin: "zhēn de ma?",
    categoryId: "other",
  },
  {
    id: "starter-002-japanese",
    japanese: "私は日本人です",
    chinese: "我是日本人。",
    pinyin: "wǒ shì Rìběn rén.",
    categoryId: "other",
  },
  {
    id: "starter-003-where-from",
    japanese: "あなたは何人ですか？",
    chinese: "你是哪里人？",
    pinyin: "nǐ shì nǎlǐ rén?",
    categoryId: "other",
  },
  {
    id: "starter-004-tea",
    japanese: "お茶を一杯ください",
    chinese: "请给我一杯茶。",
    pinyin: "qǐng gěi wǒ yì bēi chá.",
    categoryId: "restaurant",
  },
  {
    id: "starter-005-restroom",
    japanese: "トイレはどこですか？",
    chinese: "洗手间在哪里？",
    pinyin: "xǐshǒujiān zài nǎlǐ?",
    categoryId: "other",
  },
  {
    id: "starter-006-what-is-this",
    japanese: "これは何ですか？",
    chinese: "这是什么？",
    pinyin: "zhè shì shénme?",
    categoryId: "shopping",
  },
  {
    id: "starter-007-excuse-me",
    japanese: "すみません",
    chinese: "不好意思。",
    pinyin: "bù hǎo yìsi.",
    categoryId: "other",
  },
  {
    id: "starter-008-no-problem",
    japanese: "大丈夫です",
    chinese: "没关系。",
    pinyin: "méi guānxi.",
    categoryId: "other",
  },
  {
    id: "starter-009-chinese-not-good",
    japanese: "中国語があまり上手ではありません",
    chinese: "我的中文不太好。",
    pinyin: "wǒ de Zhōngwén bú tài hǎo.",
    categoryId: "other",
  },
  {
    id: "starter-010-english",
    japanese: "英語を話せますか？",
    chinese: "你会说英语吗？",
    pinyin: "nǐ huì shuō Yīngyǔ ma?",
    categoryId: "other",
  },
  {
    id: "starter-011-price",
    japanese: "いくらですか？",
    chinese: "多少钱？",
    pinyin: "duōshao qián?",
    categoryId: "shopping",
  },
  {
    id: "starter-012-this-one",
    japanese: "これをください",
    chinese: "我要这个。",
    pinyin: "wǒ yào zhège.",
    categoryId: "shopping",
  },
  {
    id: "starter-013-recommendation",
    japanese: "おすすめは何ですか？",
    chinese: "你推荐什么？",
    pinyin: "nǐ tuījiàn shénme?",
    categoryId: "restaurant",
  },
  {
    id: "starter-014-not-spicy",
    japanese: "辛くしないでください",
    chinese: "不要辣。",
    pinyin: "bú yào là.",
    categoryId: "restaurant",
  },
  {
    id: "starter-015-check",
    japanese: "会計をお願いします",
    chinese: "买单。",
    pinyin: "mǎi dān.",
    categoryId: "restaurant",
  },
  {
    id: "starter-016-wait",
    japanese: "ちょっと待ってください",
    chinese: "请等一下。",
    pinyin: "qǐng děng yíxià.",
    categoryId: "other",
  },
].map((phrase) => ({
  ...phrase,
  explanation: "",
  audioUrl: null,
  createdAt: STARTER_CREATED_AT,
  direction: "ja-to-zh",
  shouldDrill: true,
  source: "prototype",
  usedAt: null,
}));
